name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
           /opt/hostedtoolcache/Python/3.7.11/x64/bin/python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip freeze
       
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=datapreprocessingGUI" >> $GITHUB_ENV


    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: datapreprocessingGUI

    - uses: actions/upload-artifact@v2
      with:
        name: datapreprocessingGUI
        path: datapreprocessingGUI/dist/windows
