name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
       
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=datapreprocessingGUI" >> $GITHUB_ENV


    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: datapreprocessingGUI

    - uses: actions/upload-artifact@v2
      with:
        name: datapreprocessingGUI
        path: datapreprocessingGUI/dist/windows
